version: '3'
services:
  webapp:
    restart: always
    build:
      context: .
      args:
        - no-cache
    container_name: "${CONTAINER_NAME}"
    # env_file: .env
    # volumes:
    #  - ./vol:/root
    ports:
      - "8080:${NODEAPP_PORT}"
